### PR TITLE
Jcs/sinc with tinny tim

### PR DESCRIPTION
**Pull request by jSylvestre**

### CODE REVIEW

**Comment by srkirkland** [comment]
@taylorkj @jSylvestre assuming we don't care about primary instructors, which we currently do not, would this change solve the problem?

**Comment by jSylvestre** [comment]
@srkirkland @taylorkj Ken did a change the other day adding Distinct, so if they are all none primary it should fix it. I'm open to other fixes, but this seems the simplest.

**Comment by taylorkj** [comment]
@srkirkland @jSylvestre :  I'll go ahead and propose a change that will select the top 1 primary ind for a particular instructor, course, term combination.  That way the primary ind will still function as it was intended just in case it is used or will be used in the future.  That way we won't have to go back and try to figure out why it's no longer working.  Probably the safest solution.

**Comment by taylorkj** [comment]
@srkirkland @jSylvestre:  Here is the revised code. I have tested it and it works as desired.  See my notes in the commit as to how it works.  @jSylvestre: It's ready for merging as far as I am concerned.

**Pull request merged**
